services:

  portfolio:
    build:
      context: ./myportfolio
    container_name: myportfolio
    ports:
      - "80:80"
    restart: unless-stopped

  java-app:
    build:
      context: ./java-app
    container_name: java-app
    ports:
      - "8081:8080"
    restart: unless-stopped
